### ISSUE TITLE
R CMD check note on Undefined global functions or variables

### ISSUE THREAD

**Issue by obricard** [obricard/cleanhop#1]
@lgatto
I have a R CMD check note which I fail to correct.
Can you have a look at it ?

checking R code for possible problems ... NOTE
  indexplot: no visible global function definition for ‘colData<-’
  indexplot: no visible binding for global variable ‘goi_counts’
  Undefined global functions or variables:
    colData<- goi_counts

Thanks

**Comment by lgatto** [comment]
1. You probably need to import `colData<-` from `SummarizedExperiment`
2. I suspect that `goi_counts` is the name of a variable in a `data.frame` and the NOTE stems from a call to `ggplot`. You can add `goi_counts <- NULL` at the beginning of your function to get rid of that note. Another option would be to use [`.data`](https://rlang.r-lib.org/reference/tidyeval-data.html). There are probably other (such as `globalVariales()`) that I haven't tried out myself.

**Comment by obricard** [comment]
1. I changed the way of creating the data.frame for ggplot and it resolved the note. 
2. goi_counts <- NULL worked well
